### ISSUE TITLE
2020-04-06 怎么使用moco-runner进行moco接口测试

### ISSUE THREAD

**Issue by lucky-star-2020** [RainyJiang22/One-Question-Daily#11]

**Comment by lucky-star-2020** [comment]
1、配置jdk，下载moco-runner-0.11.0-standalone.jar文件
2、新建文件夹，将moco-runner-0.11.0-standalone.jar文件放置此目录，并在该目录新建json文件，此文件作为moco的配置文件。
配置文件的内容为：
[{
    "description":"这是一个带参数的get请求",
    "request":
        {
            "method":"get",
            "uri":"/login"
        },
    "response":
        {
            "text":"返回这是一个带参数的get请求"
        }
}]
//description是描述，request是请求，uri是请求路径，response是返回结果，text是返回的是文本类型内容
3、运行jar包，启动moco-runner服务。要运行该命令需要使用cd命令切换目录到jar包所在的目录。
命令为：java -jar moco-runner-0.12.0-standalone.jar http -p 自定义要访问的端口 -c 配置文件名
其中：java -jar 是启动jar文件命令，http -p 是访问协议和访问端口号，-c 是模拟的接口文件
4、启动之后，若配置文件为上述内容，则访问http://localhost:自定义的端口号/login这个链接，返回信息为：返回这是一个带参数的get请求。则已经moco成功。

有一个疑惑，moco-runner是否能mocoIP地址不是本机的接口，照上述操作moco的接口的IP地址为本机的ip地址。

**Comment by lucky-star-2020** [comment]
1、配置jdk，下载moco-runner-0.11.0-standalone.jar文件
2、新建文件夹，将moco-runner-0.11.0-standalone.jar文件放置此目录，并在该目录新建json文件，此文件作为moco的配置文件。
配置文件的内容为：
[{
    "description":"这是一个带参数的get请求",
    "request":
        {
            "method":"get",
            "uri":"/login"
        },
    "response":
        {
            "text":"返回这是一个带参数的get请求"
        }
}]
//description是描述，request是请求，uri是请求路径，response是返回结果，text是返回的是文本类型内容
3、运行jar包，启动moco-runner服务。要运行该命令需要使用cd命令切换目录到jar包所在的目录。
命令为：java -jar moco-runner-0.12.0-standalone.jar http -p 自定义要访问的端口 -c 配置文件名
其中：java -jar 是启动jar文件命令，http -p 是访问协议和访问端口号，-c 是模拟的接口文件
4、启动之后，若配置文件为上述内容，则访问http://localhost:自定义的端口号/login这个链接，返回信息为：返回这是一个带参数的get请求。则已经moco成功。

有一个疑惑，moco-runner是否能mocoIP地址不是本机的接口，照上述操作moco的接口的IP地址为本机的ip地址。

**Comment by RainyJiang22** [comment]
建议可以详细可以看下github的官方文档https://github.com/dreamhead/moco/tree/master/moco-doc
对于是否可以moco IP地址不是本机ip，当然是可以的，这就需要你自己搭建一个测试服务器里，别人访问时提供别人本机ip就可以了

**Comment by LeeJackWho** [comment]
没用过，但能找到如下内容：https://my.oschina.net/u/3823827/blog/4815875

**Comment by lucky-star-2020** [comment]
> 没用过，但能找到如下内容：https://my.oschina.net/u/3823827/blog/4815875

和我在csdn看到的教程差不多
